description = "Unit tests for Dynamo Ada Generator"
name = "dynamo_tests"
version = "1.5.0"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["dynamo_tests.gpr"]
website = "https://gitlab.com/stcarrez/dynamo"

[[depends-on]]
utilada = "^2.6.0"
serverfaces = "*"
serverfaces_unit = "*"
utilada_unit = "^2.6.0"

[configuration]
disabled = true

[[pins]]
dynamo = { path = '..' }
