<f:view xmlns:h="http://java.sun.com/jsf/html"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:fn="http://java.sun.com/jsp/jstl/functions"
        xmlns:g="http://code.google.com/p/ada-ado/generator"
        xmlns:f="http://java.sun.com/jsf/core"
        file="Makefile">
NAME=#{moduleName}
#{''}

LIBNAME=lib${NAME}
#{''}

include ../../Make-Config.mk
#{''}

GPRPATH=#{moduleName}.gpr
</f:view>
